### ISSUE TITLE
Can't add Users

### ISSUE THREAD

**Issue by Spomsoree** [dantleech/bolt-fixtures#5]
Is there a way to use this extension to automatically add users?
I can't get it running.

> Type error: Argument 2 passed to Bolt\Storage\Mapping\ContentType::__construct() must be of the type array, boolean given, called in [...]/vendor/bolt/bolt/src/Storage/ContentLegacyService.php on line 52

is the Error I get with the following example:

```
users:
    bob:
        username: bob
        password: bob
        email: 'bob@bob.de'
        displayname: bob
        enabled: true
```
